### ISSUE TITLE
`gtk2passwordapp` fails to start due to `rafini` error: `anonymous block parameter is also used within block (SyntaxError)`

### ISSUE THREAD

**Issue by barracuda156** [carlosjhr64/gtk2passwordapp#1]
Could you say what goes wrong here?

```
% /opt/local/libexec/ruby3.3/gtk2passwordapp
<internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': 
/opt/local/lib/ruby3.3/gems/3.3.0/gems/rafini-3.3.230213/lib/rafini/exception.rb:56: anonymous block parameter is also used within block (SyntaxError)
	from <internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk3app-5.4.230109/lib/gtk3app/program.rb:132:in `singleton class'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk3app-5.4.230109/lib/gtk3app/program.rb:2:in `<module:Gtk3App>'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk3app-5.4.230109/lib/gtk3app/program.rb:1:in `<top (required)>'
	from <internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk3app-5.4.230109/lib/gtk3app.rb:18:in `<module:Gtk3App>'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk3app-5.4.230109/lib/gtk3app.rb:13:in `<top (required)>'
	from <internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/opt/local/lib/ruby3.3/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk2passwordapp-6.3.230117/lib/gtk2passwordapp.rb:39:in `gui'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk2passwordapp-6.3.230117/bin/gtk2passwordapp:14:in `<class:Gtk2PasswordApp>'
	from /opt/local/lib/ruby3.3/gems/3.3.0/gems/gtk2passwordapp-6.3.230117/bin/gtk2passwordapp:3:in `<top (required)>'
	from /opt/local/libexec/ruby3.3/gtk2passwordapp:25:in `load'
	from /opt/local/libexec/ruby3.3/gtk2passwordapp:25:in `<main>'
```

**Comment by carlosjhr64** [comment]
Sorry I didn't notice this issue earlier.
Anonymous block forwarding is a feature introduced in Ruby 3.1.
My guess is that you were using version 2.
Rubygems now comes with a required_ruby_version field,
so that will stop these types of mismatch in the future.
I'll be updating my all my gems with this new field hopefully by next year.
Sorry about the inconvenience.

**Comment by carlosjhr64** [comment]
And I'm pretty sure I can close this.
